docs : amend guide
IRobot-Algorithm/GUIDE pull request #18
Opened 2024-08-31 13:50 UTC by QwQsCC

@vanitaskey

2024-08-31 14:49 UTC, Gy920 requested changes

2024-08-31 14:49 UTC, Gy920 commented on README.md
> +| v1.4 | 2024-9-1 | 关超，2533290454@qq.com | 添加工程进阶                                                |
日期改一下 2023-09-01，把下面的2024-3-22也改一下

2024-08-31 14:49 UTC, Gy920 commented on README.md
> +### 1.4 工程进阶（非必须）
去掉非必须

2024-08-31 14:49 UTC, Gy920 commented on README.md
> +4. 推理框架
推理框架应该放到深度学习方向里面

2024-08-31 14:49 UTC, Gy920 commented on README.md
> +5. GPU 编程基础
GPU编程基础也应该丢到深度学习方向里面

2024-08-31 14:49 UTC, Gy920 commented on README.md
> +   1. [TBB官方教程](https://www.intel.com/content/www/us/en/docs/onetbb/get-started-guide/2021-12/overview.html)
这里给个课会不会好一些

2024-08-31 14:49 UTC, Gy920 commented on README.md
> +6. Docker 基础
添加assets中教程

2024-08-31 14:49 UTC, Gy920 commented on README.md
> +#### 2.2.3 仿真方向（等待补充）
没补充就先不加，而且为啥这是SLAM方向下

2024-08-31 14:49 UTC, Gy920 commented on assets/其他 docker 常用方法.md
> +## ---共享图形化界面---
添加作者

2024-08-31 14:49 UTC, Gy920 commented on assets/程序性能检测可视化/程序性能检测可视化.md
> +## ---`gprof`---
添加作者

2024-08-31 14:49 UTC, Gy920 commented on assets/静态代码分析工具/静态代码分析工具.md
> +`cppcheck`、Clang Static Analyze
添加作者。而且这一句话需要单独开一个md么？

2024-08-31 14:49 UTC, Gy920 commented on assets/其他 docker 常用方法.md
> +[docker hub nvidia 官方链接](https://hub.docker.com/r/nvidia/cuda/)
docker hub好像拉不下东西了

2024-08-31 14:49 UTC, Gy920 commented on assets/程序性能检测可视化/程序性能检测可视化.md
> +![output.png](./output.png)
这个png的位置为啥不放assets/imgs里面

2024-08-31 14:49 UTC, Gy920 commented on assets/程序性能检测可视化/程序性能检测可视化.md
> +gprof ./name gmon.out > output.txt
这个output.txt给个示例？

2024-08-31 14:49 UTC, Gy920 commented on assets/其他 docker 常用方法.md
> +### 1,Ubuntu(20.10以上)环境下
为啥这是逗号 1，

2024-08-31 14:52 UTC, Gy920 commented on README.md
> +6. Docker 基础
> 添加assets中教程
指的是docker

2024-08-31 14:52 UTC, Gy920 commented on README.md
> +   1. [TBB官方教程](https://www.intel.com/content/www/us/en/docs/onetbb/get-started-guide/2021-12/overview.html)
> Member
指的是TBB OpenMP

2024-08-31 14:54 UTC, Gy920 commented
而且你加了代码性能分析的md，文中好像没有提到？

2024-08-31 14:59 UTC, QwQsCC commented on README.md
> +   1. [TBB官方教程](https://www.intel.com/content/www/us/en/docs/onetbb/get-started-guide/2021-12/overview.html)
这俩个东西的教程有点少，基本就靠官方文档了

2024-08-31 15:02 UTC, QwQsCC commented on assets/其他 docker 常用方法.md
> +### 1,Ubuntu(20.10以上)环境下
这里和下面的命令是一起的，写的有点不太好

2024-08-31 15:17 UTC, QwQsCC commented on assets/静态代码分析工具/静态代码分析工具.md
> +`cppcheck`、Clang Static Analyze
抱歉这个搞错了，这个还没写好

2024-08-31 15:18 UTC, Gy920 commented on README.md
> +   1. [TBB官方教程](https://www.intel.com/content/www/us/en/docs/onetbb/get-started-guide/2021-12/overview.html)
我感觉这个[课]( https://github.com/parallel101/course)不错

2024-08-31 15:30 UTC, QwQsCC commented on README.md
> +   1. [TBB官方教程](https://www.intel.com/content/www/us/en/docs/onetbb/get-started-guide/2021-12/overview.html)
收到，已经加入资料队列中了

2024-08-31 15:33 UTC, QwQsCC commented on assets/其他 docker 常用方法.md
> +[docker hub nvidia 官方链接](https://hub.docker.com/r/nvidia/cuda/)
这个后面补充拉不下来的解决方法了

2024-08-31 15:40 UTC, QwQsCC commented on assets/程序性能检测可视化/程序性能检测可视化.md
> +![output.png](./output.png)
将不同笔记的图片区分开感觉更方便管理

2024-08-31 15:41 UTC, QwQsCC commented on README.md
> +#### 2.2.3 仿真方向（等待补充）
OK，添加的时候目录搞错了/捂脸

2024-08-31 15:48 UTC, QwQsCC commented
感谢@Gy920 学长，文档错误已经基本修正，请求合并@S-Canister ,@niuoruo ,@BoZhiStudying233

2024-09-01 07:02 UTC, Gy920 commented on README.md
> +   1. CUDA
这个推理框架和上面的"yolo后端推理"(顺便把这个名字改了）那块合起来吧,没必要单独拉一点，然后GPU编程基础放在研究方向建议里会不会更合适？

2024-09-01 09:58 UTC, QwQsCC commented on README.md
> +   1. CUDA
抱歉，写前面那部分的时候看漏了已经将推理部署部分合并了

2024-09-01 11:44 UTC, Gy920 commented on README.md
> +   7.  GPU 编程基础
改成 _7. GPU 编程基础（CUDA，OpenGL)_  会不会好一点

2024-09-01 11:45 UTC, Gy920 commented on README.md
> +| v1.4 | 2024-9-1 | 关超，2533290454@qq.com | 添加工程进阶                                                |
@QwQsCC  以及这个时间，和其他你新增文档的时间

2024-09-01 15:38 UTC, S-Canister approved these changes

2024-09-02 03:08 UTC, niuoruo commented on README.md
> +| v1.4 | 2024-9-1 | 关超，2533290454@qq.com | 添加工程进阶                                                |
@QwQsCC 这里格式还没改2024-09-01，和底下日期对齐一下，段智博的也帮忙改一下2024-03-22

2024-09-02 03:12 UTC, niuoruo commented on assets/其他 docker 常用方法.md
> +| v1.0 | 2024-9-01 | 关超, 23049200367@qq.com  | 添加其他docker常用方法文档          |
这里日期格式也可以改一下

2024-09-02 13:35 UTC, QwQsCC commented on assets/其他 docker 常用方法.md
> +| v1.0 | 2024-9-01 | 关超, 23049200367@qq.com  | 添加其他docker常用方法文档          |
好的，已经全部修改完成

2024-09-02 13:35 UTC, QwQsCC commented on README.md
> +| v1.4 | 2024-9-1 | 关超，2533290454@qq.com | 添加工程进阶                                                |
已经修改完成

2024-09-02 13:41 UTC, merged